# Generated by Django 2.0.2 on 2018-10-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Place', models.CharField(max_length=100)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Catagorie')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('My_share', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Friends_share', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
