# Generated by Django 2.0.2 on 2018-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('My_share', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Friends_share', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='money',
            new_name='Money',
        ),
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
