# Generated by Django 2.0.2 on 2018-10-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20181009_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Friends_Count', models.IntegerField()),
                ('Place', models.CharField(max_length=20)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Catagorie')),
            ],
        ),
    ]
