# Generated by Django 2.0.2 on 2018-10-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='Friends_Count',
            new_name='Count',
        ),
    ]
