# Generated by Django 2.0.2 on 2018-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20181009_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='Date',
            field=models.DateField(),
        ),
    ]
